# Generated by Django 5.0.4 on 2024-04-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flavor',
            field=models.CharField(max_length=30),
        ),
    ]
